DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 3
SectionPagesMenu = "main"
baseURL = "/"
disqusShortname = "ananke-demo"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en"
theme = "gohugo-theme-ananke"
title = "Ananke"
[params]
background_color_class = "bg-black"
description = "The last theme you'll ever need. Maybe."
faceboook = ""
featured_image = "/uploads/2018/05/01/bitcoins-wallpaper.jpg"
instagram = ""
twitter = "https://twitter.com/GoHugoIO"
youtube = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
